# Tensor basics - indexing and slicing

### Dr. Tirthajyoti Sarkar<br><br>Fremont, CA 94536 <br><br>April 2019

In [1]:
import torch
import numpy as np

In [2]:
c = torch.Tensor([i for i in range(5)])

In [3]:
c

tensor([0., 1., 2., 3., 4.])

### Accessing element

In [4]:
c[0]

tensor(0.)

In [5]:
c[2]

tensor(2.)

### Changing element

In [6]:
c[0]=100

In [7]:
c

tensor([100.,   1.,   2.,   3.,   4.])

In [8]:
c[4]=-100

In [9]:
c

tensor([ 100.,    1.,    2.,    3., -100.])

### Slicing a part of the tensor

In [10]:
d = c[1:4]

In [11]:
d

tensor([1., 2., 3.])

### Changing a slice (portion) of the tensor

In [12]:
c

tensor([ 100.,    1.,    2.,    3., -100.])

In [14]:
c[1:4] = torch.Tensor([11,12,13])

In [15]:
c

tensor([ 100.,   11.,   12.,   13., -100.])