# Tensor basics - Matrix (2-D) operations

### Dr. Tirthajyoti Sarkar<br><br>Fremont, CA 94536 <br><br>April 2019

In [1]:
import torch
import numpy as np

### Creating 2-D Tensor (aka Matrix)

In [13]:
lst_of_lst = []

for i in range(3):
    inner_lst=[]
    for j in range(3):
        inner_lst.append(10*(i+1)+j)
    lst_of_lst.append(inner_lst)

In [14]:
lst_of_lst

[[10, 11, 12], [20, 21, 22], [30, 31, 32]]

In [15]:
A = torch.tensor(lst_of_lst)

In [16]:
A

tensor([[10, 11, 12],
        [20, 21, 22],
        [30, 31, 32]])

### Dimension, shape and size of the 2-D Tensor

In [18]:
print("Dimension of the tensor:",A.ndimension())

Dimension of the tensor: 2


In [21]:
# shape is an attribute of the tensor
print("Shape of the tensor:",A.shape)

Shape of the tensor: torch.Size([3, 3])


In [26]:
# size is a function/method which returns the size/shape of the tensor
print("Total size of the tensor:",A.size())

Total size of the tensor: torch.Size([3, 3])


### Total number of elements can be found by casting the `size` attribute to an ndarray and then applying `prod`

In [28]:
print("Total size of the tensor:",np.array(A.size()).prod())

Total size of the tensor: 9


### Matrix (tensor) addition

In [29]:
lst_of_lst = []

for i in range(3):
    inner_lst=[]
    for j in range(4):
        inner_lst.append(10*(i+1)+j)
    lst_of_lst.append(inner_lst)

In [30]:
A = torch.tensor(lst_of_lst)

In [32]:
A

tensor([[10, 11, 12, 13],
        [20, 21, 22, 23],
        [30, 31, 32, 33]])

In [33]:
lst_of_lst = []

for i in range(3):
    inner_lst=[]
    for j in range(4):
        inner_lst.append(10*(i+1)-j)
    lst_of_lst.append(inner_lst)

In [34]:
B = torch.tensor(lst_of_lst)

In [35]:
B

tensor([[10,  9,  8,  7],
        [20, 19, 18, 17],
        [30, 29, 28, 27]])

$$ \begin{bmatrix}
10 & 11 & 12 & 13\\ 20 & 21 & 22 & 23 \\ 30 & 31 & 32 & 33 \end{bmatrix} + \begin{bmatrix}
10 & 9 & 8 & 7\\ 20 & 19 & 18 & 17 \\ 30 & 29 & 28 & 27 \end{bmatrix} = \begin{bmatrix}
20 & 20 & 20 & 20\\ 40 & 40 & 40 & 40 \\ 60 & 60 & 60 & 60 \end{bmatrix}$$

In [37]:
C=A+B

In [38]:
C

tensor([[20, 20, 20, 20],
        [40, 40, 40, 40],
        [60, 60, 60, 60]])

### Multiplying matrix by a scalar

In [41]:
D = 2.2*A

In [42]:
D

tensor([[20, 22, 24, 26],
        [40, 42, 44, 46],
        [60, 62, 64, 66]])

#### The result is not exactly as we expected because A had the `IntTensor` type. We have to convert `A` to a `FloatTensor` type

In [45]:
A = A.type(torch.FloatTensor)

In [46]:
D = 2.2*A

In [47]:
D

tensor([[22.0000, 24.2000, 26.4000, 28.6000],
        [44.0000, 46.2000, 48.4000, 50.6000],
        [66.0000, 68.2000, 70.4000, 72.6000]])

### Adding a scalar to a matrix

In [61]:
E = A+5.5

In [62]:
E

tensor([[15.5000, 16.5000, 17.5000, 18.5000],
        [25.5000, 26.5000, 27.5000, 28.5000],
        [35.5000, 36.5000, 37.5000, 38.5000]])

### Slicing and indexing matrix elements

In [48]:
A

tensor([[10., 11., 12., 13.],
        [20., 21., 22., 23.],
        [30., 31., 32., 33.]])

In [51]:
A[0,0]

tensor(10.)

In [52]:
A[2,1:3]

tensor([31., 32.])

In [53]:
A[:2,1:3]

tensor([[11., 12.],
        [21., 22.]])

In [58]:
A[0:3,[0,2]]

tensor([[10., 12.],
        [20., 22.],
        [30., 32.]])

### Element-wise product of matrices

In [69]:
X = torch.tensor([[1,2,-1],[3.5,0,1],[7,3,-2]])

In [70]:
Y = torch.tensor([[4,1,-3],[4,5,2.4],[7.5,-3,5]])

In [71]:
X

tensor([[ 1.0000,  2.0000, -1.0000],
        [ 3.5000,  0.0000,  1.0000],
        [ 7.0000,  3.0000, -2.0000]])

In [72]:
Y

tensor([[ 4.0000,  1.0000, -3.0000],
        [ 4.0000,  5.0000,  2.4000],
        [ 7.5000, -3.0000,  5.0000]])

In [73]:
Z = X*Y

In [74]:
Z

tensor([[  4.0000,   2.0000,   3.0000],
        [ 14.0000,   0.0000,   2.4000],
        [ 52.5000,  -9.0000, -10.0000]])

### Matrix multiplication (shape of the individual tensors must line up accordingly)

In [120]:
X = torch.tensor([[1,2.5],[3.5,0],[11,2]])

In [121]:
X

tensor([[ 1.0000,  2.5000],
        [ 3.5000,  0.0000],
        [11.0000,  2.0000]])

In [122]:
Y = torch.tensor([[4,1,-3],[1.7,5,2.4]])

In [123]:
Y

tensor([[ 4.0000,  1.0000, -3.0000],
        [ 1.7000,  5.0000,  2.4000]])

In [124]:
W = X.mm(Y)

In [125]:
W

tensor([[  8.2500,  13.5000,   3.0000],
        [ 14.0000,   3.5000, -10.5000],
        [ 47.4000,  21.0000, -28.2000]])

### Matrix transpose
Need to specify the dimensions as `dim0`, `dim1` argument to the method

In [126]:
W

tensor([[  8.2500,  13.5000,   3.0000],
        [ 14.0000,   3.5000, -10.5000],
        [ 47.4000,  21.0000, -28.2000]])

In [127]:
W.transpose(0,1)

tensor([[  8.2500,  14.0000,  47.4000],
        [ 13.5000,   3.5000,  21.0000],
        [  3.0000, -10.5000, -28.2000]])

### Matrix inverse and determinant

In [137]:
X = torch.tensor([[2.5,1.2],[3,2]])
Y = torch.tensor([[1.2,-1],[2,3]])

In [138]:
W = torch.mm(X,Y)

In [139]:
W

tensor([[5.4000, 1.1000],
        [7.6000, 3.0000]])

In [140]:
torch.inverse(W)

tensor([[ 0.3827, -0.1403],
        [-0.9694,  0.6888]])

In [141]:
torch.det(W)

tensor(7.8400)