# Tensor basics - creation and conversion

### Dr. Tirthajyoti Sarkar<br><br>Fremont, CA 94536 <br><br>April 2019

In [113]:
import torch
import numpy as np
import pandas as pd

### 1-D Tensor from a list

In [121]:
a = torch.tensor([i for i in range(5)])

In [122]:
a

tensor([0, 1, 2, 3, 4])

In [123]:
type(a)

torch.Tensor

In [124]:
a.dtype

torch.int64

In [125]:
a.type()

'torch.LongTensor'

### Acessing element (indexing) and data type

In [126]:
a[0]

tensor(0)

In [127]:
a[3]

tensor(3)

### Accessing the actual number using `item()` method

In [128]:
a[2].item()

2

In [129]:
type(a[3].item())

int

### Creating a `torch.FloatTensor` using `FloatTensor()` method

In [33]:
a = torch.tensor([1.0,2.0,3.0,4.0,5.0])

In [35]:
a.type()

'torch.FloatTensor'

In [36]:
a = torch.FloatTensor([1,2,3,4,5])

In [37]:
a.type()

'torch.FloatTensor'

### Converting from a `LongTensor` using `type` method

In [25]:
b = torch.tensor([i for i in range(5)])

In [26]:
b

tensor([0, 1, 2, 3, 4])

In [27]:
b.dtype

torch.int64

In [28]:
b.type()

'torch.LongTensor'

In [29]:
b = b.type(torch.FloatTensor)

In [30]:
b

tensor([0., 1., 2., 3., 4.])

In [31]:
b.dtype

torch.float32

In [32]:
b.type()

'torch.FloatTensor'

### Size and dimension

In [44]:
b

tensor([0., 1., 2., 3., 4.])

In [45]:
b.size()

torch.Size([5])

In [46]:
b.ndimension()

1

### Changing the view of a tensor

In [54]:
a = torch.tensor([i for i in range(1,6)])

In [55]:
a

tensor([1, 2, 3, 4, 5])

In [63]:
a.size()

torch.Size([5])

In [56]:
a.ndimension()

1

In [57]:
a_col = a.view(5,1)

In [58]:
a_col

tensor([[1],
        [2],
        [3],
        [4],
        [5]])

In [59]:
a_col.type()

'torch.LongTensor'

In [61]:
a_col.ndimension()

2

In [62]:
a_col.size()

torch.Size([5, 1])

### If we don't know the original size, we can use -1 as placeholder

In [86]:
n = [6, 9, 12]
for k in n:
    a = torch.tensor([i for i in range(k)])
    a_col = a.view(-1,3)
    print("Original tensor:", a)
    print("Reshaped view of tensor with 3 columns:\n",a_col)
    print("="*40)

Original tensor: tensor([0, 1, 2, 3, 4, 5])
Reshaped view of tensor with 3 columns:
 tensor([[0, 1, 2],
        [3, 4, 5]])
Original tensor: tensor([0, 1, 2, 3, 4, 5, 6, 7, 8])
Reshaped view of tensor with 3 columns:
 tensor([[0, 1, 2],
        [3, 4, 5],
        [6, 7, 8]])
Original tensor: tensor([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11])
Reshaped view of tensor with 3 columns:
 tensor([[ 0,  1,  2],
        [ 3,  4,  5],
        [ 6,  7,  8],
        [ 9, 10, 11]])


### Changing back and forth between tensor and `NumPy` array

In [105]:
np_array = np.arange(1.0,3.5,0.5)

In [106]:
np_array

array([1. , 1.5, 2. , 2.5, 3. ])

In [107]:
tensor_from_array = torch.from_numpy(np_array)

In [108]:
tensor_from_array

tensor([1.0000, 1.5000, 2.0000, 2.5000, 3.0000], dtype=torch.float64)

In [109]:
tensor_from_array.type()

'torch.DoubleTensor'

In [110]:
back_to_np = tensor_from_array.numpy()

In [111]:
back_to_np

array([1. , 1.5, 2. , 2.5, 3. ])

### Pointer from re-converted numpy array points to the tensor object, which, in turn, points to the original numpy array. So, any change in the original numpy array reflects back.

In [112]:
np_array

array([1. , 1.5, 2. , 2.5, 3. ])

In [101]:
np_array

array([2., 3., 4., 5., 6.])

In [102]:
back_to_np

array([1. , 1.5, 2. , 2.5, 3. ])

In [103]:
tensor_from_array

tensor([1.0000, 1.5000, 2.0000, 2.5000, 3.0000], dtype=torch.float64)

### Conversion from a Pandas series

In [114]:
pd_series = pd.Series([i for i in range(1,6)])

In [115]:
pd_series

0    1
1    2
2    3
3    4
4    5
dtype: int64

In [117]:
pd_to_torch = torch.from_numpy(pd_series.values)

In [118]:
pd_to_torch

tensor([1, 2, 3, 4, 5])

### Converting back to a list using `tolist()`

In [119]:
to_list = pd_to_torch.tolist()

In [120]:
to_list

[1, 2, 3, 4, 5]