# Tensor basics - Vector (1-D) operations

### Dr. Tirthajyoti Sarkar<br><br>Fremont, CA 94536 <br><br>April 2019

In [1]:
import torch
import numpy as np

### Vector (tensor) addition

In [2]:
u = torch.Tensor([1,0])
v = torch.Tensor([0,1])

In [3]:
u

tensor([1., 0.])

In [4]:
v

tensor([0., 1.])

In [5]:
w = u+v

In [6]:
w

tensor([1., 1.])

### Vector multiplication with a scalar

In [7]:
y = torch.Tensor([[1],[2]])

In [8]:
y

tensor([[1.],
        [2.]])

In [9]:
z= 1.5*y

In [10]:
z

tensor([[1.5000],
        [3.0000]])

### Linear combination

In [28]:
u = torch.Tensor([1,2])
v = torch.Tensor([3,-1])

$$2\times\begin{bmatrix}
1 & 2
\end{bmatrix}+3\times\begin{bmatrix}
3 & -1
\end{bmatrix}$$ = $$\begin{bmatrix}
11 & -1
\end{bmatrix}$$

In [31]:
w = 2*u+3*v

In [32]:
w

tensor([11.,  1.])

### Product (element-wise) of two tensors

In [33]:
u = torch.Tensor([[1],[3]])
v = torch.Tensor([[2],[4]])

In [34]:
u

tensor([[1.],
        [3.]])

In [35]:
v

tensor([[2.],
        [4.]])

$$ u=\begin{bmatrix}
1 \\ 3 \end{bmatrix}, \ \ v=\begin{bmatrix}
2 \\ 4 \end{bmatrix} $$

$$ u*v = \begin{bmatrix}
1\times 2 \\ 3\times 4 \end{bmatrix}= \begin{bmatrix}
2 \\ 12 \end{bmatrix}$$

In [36]:
z = u*v

In [37]:
z

tensor([[ 2.],
        [12.]])

### DOT product using `dot` method

In [38]:
u = torch.Tensor([1,2])
v = torch.Tensor([3,1])

In [39]:
u

tensor([1., 2.])

In [40]:
v

tensor([3., 1.])

In [41]:
torch.dot(u,v)

tensor(5.)

### Matrix multiplication between tensors.
Remember to use reshape the tensors using the `reshape()` method to ensure proper matrix multiplication

In [45]:
u = torch.Tensor([1,2])
v = torch.Tensor([[3],[1]])

In [46]:
u

tensor([1., 2.])

In [47]:
u = u.reshape(2,1)
v = v.reshape(1,2)

In [48]:
u

tensor([[1.],
        [2.]])

In [49]:
u.shape

torch.Size([2, 1])

In [50]:
v.shape

torch.Size([1, 2])

In [51]:
z = torch.mm(u,v)

In [52]:
z

tensor([[3., 1.],
        [6., 2.]])

### Adding a scalar to a tensor (also known as broadcasting)

In [53]:
u = torch.Tensor([1,2,3,4])

In [54]:
u

tensor([1., 2., 3., 4.])

In [55]:
z=u+10

In [56]:
z

tensor([11., 12., 13., 14.])